M48
; DRILL file {KiCad (6.0.5)} date Thu 02 Jun 2022 10:53:17 AM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-02T10:53:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X118.32Y-83.82
X118.32Y-132.82
X176.32Y-83.82
X176.32Y-132.82
T0
M30
